from .TerminalEntero import TerminalEntero
from .TerminalGenerico import TerminalGenerico
from .TerminalIdentificador import TerminalIdentificador
from .TerminalCadena import TerminalCadena
from .TerminalDecimal import TerminalDecimal
from .TerminalBool import TerminalBool
from .Terminalexp import Terminalexp
from .TerminalChar import TerminalChar
from .TerminalArreglo import TerminalArreglo
from .TerminalArreglo2 import TerminalArreglo2